name: Build FreeCAD-Libpack
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build-Libpack:
    name: Build the FreeCAD-Libpack
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        shell: pwsh
        run: |
          dir
          choco install winflexbison3
          pip install requests
          pip install diff-match-patch
      - name: Find paths for tools
        shell: pwsh
        run: |
          where 7z
          where bison
      - name: Run build command
        shell: pwsh
        run: |
          python.exe create_libpack.py
